name: Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Install golangci-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.45.2

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Check lint
      run: golangci-lint run -v

    - name: Test code
      run: go test ./...
